In [29]:
import pandas as pd

In [30]:
# 1. Refer to googleplaystore.csv file and solve following questions
df = pd.read_csv("googleplaystore.csv")

In [31]:
# a. Display First 5 records from Dataframe.
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [32]:
# b) Category with highest number of apps
df["Category"].value_counts().idxmax()

'FAMILY'

In [33]:
# c. What is the average rating for all the apps
df["Rating"].mean()

np.float64(4.193338315362443)

In [34]:
# d. Display total number of apps which even supports Andriod version 2.3 and up
len(df[df["Android Ver"].str.contains("2.3", na=False)])

933

In [35]:
# e. Impute the missing values available in rating column with respective measure
# of central tendency.
df["Rating"].fillna(df["Rating"].median(), inplace=True)

In [36]:
# 2. Refer to salaries.xlsx file and solve following questions
df = pd.read_excel("salaries.xlsx")

In [37]:
# a. Check head of the dataframe
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [38]:
# b. Find out details about no. of entries & no. of columns in the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id                1000 non-null   int64
 1   EmployeeName      1000 non-null   object
 2   JobTitle          1000 non-null   object
 3   BasePay           1000 non-null   float64
 4   OvertimePay       1000 non-null   float64
 5   OtherPay          1000 non-null   float64
 6   Benefits          0 non-null      float64
 7   TotalPay          1000 non-null   float64
 8   TotalPayBenefits  1000 non-null   float64
 9   Year              1000 non-null   int64
 10  Notes             0 non-null      float64
 11  Agency            1000 non-null   object
 12  Status            0 non-null      float64
dtypes: float64(8), int64(2), object(3)
memory usage: 101.7+ KB

In [39]:
# c. What is the average base pay?
df["BasePay"].mean()

np.float64(145663.9982)

In [40]:
# d. What is the highest amount of overtime pay in the dataset?
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"], errors="coerce")
df["OvertimePay"].max()

np.float64(245131.88)

In [41]:
# e. What is the job title of JOSEPH DRISCOLL?
df[df["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [42]:
# f. How much does JOSEPH DRISCOLL make (including benefits)?
df[df["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [43]:
# g. How many unique job titles are there?
df["JobTitle"].nunique()

113

In [44]:
# h. What are the top 5 common jobs?
df["JobTitle"].value_counts().head(5)

JobTitle
FIREFIGHTER                           133
LIEUTENANT, FIRE DEPARTMENT            62
FIRE FIGHTER PARAMEDIC                 43
CAPTAIN, FIRE SUPPRESSION              42
BATTALION CHIEF, (FIRE DEPARTMENT)     41
Name: count, dtype: int64